### ISSUE TITLE
Нарезать кронштейны для крепления материнских плат

### ISSUE THREAD

**Issue by mastersin** [boringplace/boringmodels#1]
Нужно сделать пример кронштейна по шаблону:
https://github.com/sarfsc/boringmodels/tree/master/motherboard_bracket

Собрать тестовый образец и по шагам, в несколько итераций сделать вариант кронштейн с универсальной частью крепления к стене. Ответная часть для крепления разный вариантов отладочных и компьютерных материнских плат нарезаются по мере необходимости.

**Comment by mastersin** [comment]
Запланировал на завтра нарезку силами помощников из ЦМИТ Центрит.

**Comment by gochankot** [comment]
Первая версия есть, закрыть можно пока задачу

**Comment by ghost** [comment]
Кронштейны есть, задачу закрываю.

**Comment by ghost** [comment]
А, не у меня прав закрыть нет. @mastersin , закрой задачу и репозиторий.

**Comment by mastersin** [comment]
А репозиторий зачем закрывать? Или что ты имел в виду? Наоборот, хотелось бы сделать об этом отдельную статью со ссылками на то, о том как изготовить под наши крепления свои варианты стендов, используя опубликованные в репозитории файлы с dxf-шаблонами под резку на лазерном станке.

**Comment by ghost** [comment]
Я не против статьи, просто у нас есть теперь boringplace/boringmodels. Зачем два репозитория?

**Comment by mastersin** [comment]
Я перенёс проект в другую организацию.
